/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "5.9.6"

#define QT3DQUICK_VERSION 0x050906

#endif // QT_QT3DQUICK_VERSION_H
